### ISSUE TITLE
Minor: Missing first level heading

### ISSUE THREAD

**Issue by rsgoertz** [Purple-Recovery/purple-recovery#11]
Reproduction: Accessing home page [https://purple-recovery.web.app/](url)

Homepage does not have a first level heading.

Headings facilitate page navigation for users of many assistive technologies. This presents an accessibility issue with those that depend on screen readers.

**Comment by kylerws** [comment]
ARIA labels and semantic headings are not a part of our requirements, so this is a non-failure. However, it is important to make our website as accessible as possible, so a first-level header tag has been added to the homepage.
