### ISSUE TITLE
MAJOR: Application doesn't work on Mobile

### ISSUE THREAD

**Issue by thejameskim** [Purple-Recovery/purple-recovery#2]
**Reproduction Steps:** 
Go to the application on mobile

**Description:**
All the links and text on the page are not organized and overlap each other. 

**Rationale:**
This issue is problematic because this excludes a lot of users who tend to go to web applications on their phones. 

<img width="345" alt="PurpleRecovery - Issues on Mobile" src="https://user-images.githubusercontent.com/15903829/83665650-90165100-a580-11ea-9389-9029d9618715.png">

**Comment by gcaelin30** [comment]
Hi! Actually we didn't design this to be on mobile! It isn't part of our requirements
