### ISSUE TITLE
MINOR: Design - Grouping of Articles

### ISSUE THREAD

**Issue by ShrutiR5** [Purple-Recovery/purple-recovery#3]
**Describe the bug**
There's no filter option to search for specific kinds of articles under the "RESPONSES" tab.

**Steps to reproduce the behavior:**
1. On home page click "Find Articles"
2. Go to list of articles listed.
3. No way to filter based on things such as latest vs oldest article on the list. 

**Proposed behavior**
A way in which the user can filter based on dates to find the most latest information may be useful!

Screenshot of page I am referring to: 
<img width="656" alt="Screen Shot 2020-06-03 at 5 43 47 PM" src="https://user-images.githubusercontent.com/35204568/83702649-23bc4180-a5c2-11ea-862d-58dc6d2306bd.png">

**Comment by gcaelin30** [comment]
Hi! This isn't in our requirements to have a filter on there
