### ISSUE TITLE
MINOR: sources are duplicated

### ISSUE THREAD

**Issue by rachelvuu** [Purple-Recovery/purple-recovery#4]
**Description of the issue**:
I see a lot of overlap in the sources throughout the website that might be redundant and makes the architecture confusing

**Reproduction of steps**:
1. Be on the landing page
2. Read resources under _Responses_ or  _Community_ section
3. Navigate to _Find Articles_ or _Stay Connected_
4. See that those same articles on the homepage are present with the addition of 1 link

**Rationale**: 
I think this may be worth addressing because users must navigate back and forth frequently and it may be inefficient if they don't realize they've already viewed a certain link. It may be especially unexpected because the first link on the homepage ("See All") differs such that all of the links on that page are new. 

**Additional context**: 
I like this app idea! Since important information on COVID-19 is scattered across the internet, a centralized platform drawing from authentic and relevant sources would be really useful.

**Comment by gcaelin30** [comment]
We just followed the UW convention as well.
