### ISSUE TITLE
Minor: Alternative Text

### ISSUE THREAD

**Issue by magalj** [Purple-Recovery/purple-recovery#5]
Alt text
Minor
Description:
Alt text is important for screen readers to understand the pages. While many of the small images and logos of the results do not have alternate text those probably don’t need descriptive alt text. However, the most important one might be the image with text found in the drop a note section. This image has alternate text, however ideally large chunks of text would not be pictures but actual text!
Reproduction:
1.	Click on drop a note
2.	Select top text filled image
3.	Alt text says =”Submit a Resource or Feedback”
4.	Same steps can be done with images on homepage.

**Comment by gcaelin30** [comment]
Not a requirement
