### ISSUE TITLE
MINOR: Text not contained

### ISSUE THREAD

**Issue by kevin-chiu** [Purple-Recovery/purple-recovery#6]
Describe the bug
The text on the main page is not contained and accessible if the screen is not maximized.

To Reproduce

Some of the text is already not fully contained and overlaps when the screen is maximized, but lowering the width by a little makes the behavior more apparent.

Expected behavior
I expected the text to push onto the next line, wrapping itself with the background and the container that it is encapsulated. Most importantly for users, the text should not overlap with images with similar colors that would inhibit its reading capabilities (UW Minecraft Server with the Minecraft Logo)

Screenshots
![image](https://user-images.githubusercontent.com/31137647/83928504-e46a2e00-a744-11ea-833b-92127d584b07.png)

**Comment by gcaelin30** [comment]
Duplicate issue. 3rd one about screensizes
