### ISSUE TITLE
Email ID - Minor

### ISSUE THREAD

**Issue by soham98** [Purple-Recovery/purple-recovery#7]
The website is very informative, I actually learned a lot of new stuff reading through some links, didnt know about the town hall, would recommend this to peers

**Description of the issue:**
the feedback form allows incorrect email ID'd to go through

**Reproduction of steps:**
Going to the form and typing in an email such as "test@sdfsdfsfsadfadf.com" will allow you to submit a form even though that id technically doesn't exist. 

**Rationale:**
To reduce user error of typing in a wrong email id, or just to reduce the number of spam comments having some sort of check would be useful
I don't particularly know how to solve this issue, or even if it's solvable at this level

**Comment by gcaelin30** [comment]
Not in our requirements.
