### ISSUE TITLE
MINOR: Non responsive screens

### ISSUE THREAD

**Issue by adamkpumputis** [Purple-Recovery/purple-recovery#9]
Issue:

When adjusting the screen size to a smaller size the text inside each item is not contained and overlaps with other elements. I expected the text within each card to wrap in the card and be contained within each card. Or that I would be able to scroll the page to the right to see additional cards.

Reproduction Steps:

Minimize the screen size

Screenshot:
![Screen Shot 2020-06-07 at 3 28 12 PM](https://user-images.githubusercontent.com/22605317/83981530-99325580-a8d3-11ea-979e-e062fae72546.png)

**Comment by gcaelin30** [comment]
Duplicate issue of something that was previously closed.
